{% set name = "iscd-mshdist" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # there are no tagged releases which so using archives of specific commits
  url: https://github.com/ISCDtoolbox/Mshdist/archive/refs/tags/v{{ version }}.zip
  sha256: f10f7593289440a25a0b83e87ce6ef87587192107f285e3255e629b841108e71

build:
  number: 0
  skip: true  # [py<3 or win] # "CMakeLists.txt": invalid command code C && Cannot open include file: 'pthread.h': No such file or directory 
  ignore_run_exports_from:
    - {{ compiler('cxx') }}
  run_exports:
    - {{ pin_subpackage('iscd-mshdist', max_pin='x.x.x') }}   

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake
    - make  # [not win]
    - jom  # [win]
    - iscd-commons    
  run:
    - iscd-commons

test:
  commands:
    - mshdist -h || true  # [unix]
    - test -f $PREFIX/lib/libMshdist.so  # [linux]
    - test -f $PREFIX/lib/libMshdist.dylib  # [osx]    
    - test -f $PREFIX/include/mshdist.h
    - test -f $PREFIX/include/mshdistexterns.h    

about:
  home: https://iscd.sorbonne-universite.fr/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: 'ISCD - mshdist'
  description: |
    mshdist is a simple algorithm to generate the signed distance function to given objects in two and three space dimensions.
  doc_url: https://github.com/ISCDtoolbox/Mshdist/tree/master/documentation
  dev_url: https://github.com/ISCDtoolbox/Mshdist.git

extra:
  recipe-maintainers:
    - ldallolio
    - fbordeu
